version: "3.9"

services:

    login:
        build:
            context: .
            dockerfile: Dockerfile-django-login
        container_name: login_container
        ports:
            - "8000:8000"
        depends_on:
            - postgres
        networks:
            - red
        volumes:
            - ./project:/app

    postgres:
        image: postgres:15.4-alpine3.17
        container_name: postgres_container
        ports:
            - "5432:5432"
        environment:
            - POSTGRES_USER=admin
            - POSTGRES_PASSWORD=admin
            - POSTGRES_DB=admin
        networks:
            - red
        volumes:
            - ./data:/var/lib/postgresql/data


    pgadmin:
        image: dpage/pgadmin4:latest
        container_name: pgadmin_container
        ports:
            - "5050:80"
        environment:
            - PGADMIN_DEFAULT_EMAIL=admin@admin.com
            - PGADMIN_DEFAULT_PASSWORD=admin
        networks:
            - red

networks:
    red: